// Pagefind's Component UI (public/pagefind/pagefind-component-ui.js, generated by
// build-scripts/generate-pagefind-index.mjs) registers these as real custom elements at
// runtime -- this only teaches JSX their attributes so DocsShell.tsx type-checks. Attributes
// are all HTML-attribute strings (booleans are presence-based, e.g. `autofocus=""`), per
// https://pagefind.app/docs/components/.
//
// INVARIANT: `placeholder` is deliberately NOT declared on any of these, on any element that has
// it. pagefind-modal-trigger, pagefind-input, and pagefind-searchbox all define `placeholder` as
// a getter-only accessor on their prototype (confirmed in the shipped
// pagefind-component-ui.js), backed by a *different* field (`_userPlaceholder`). React 19 sets
// known DOM-ish prop names directly as element properties when the property already exists on
// the prototype, so passing `placeholder` as a JSX prop crashes the moment React commits it --
// "Cannot set property placeholder of #<He> which has only a getter". Set it via
// element.setAttribute("placeholder", ...) from a ref callback instead (see DocsShell.tsx's
// setPagefindPlaceholder), which these components' own readAttributes() picks up correctly.
import type { DetailedHTMLProps, HTMLAttributes } from "react";

type PagefindElementProps<Extra> = DetailedHTMLProps<HTMLAttributes<HTMLElement>, HTMLElement> & Extra;

// React 19's JSX.IntrinsicElements lives under the "react" module's own React.JSX namespace
// (re-exported by react/jsx-runtime for the automatic JSX transform this app uses), not a bare
// global JSX namespace -- augmenting that global namespace (the React 18-era approach) silently
// doesn't affect what the automatic runtime actually resolves against.
declare module "react" {
  namespace JSX {
    interface IntrinsicElements {
      "pagefind-modal-trigger": PagefindElementProps<{
        instance?: string;
        shortcut?: string;
        "hide-shortcut"?: string;
        compact?: string;
      }>;
      "pagefind-modal": PagefindElementProps<{
        instance?: string;
        "reset-on-close"?: string;
      }>;
      "pagefind-input": PagefindElementProps<{
        instance?: string;
        debounce?: string;
        autofocus?: string;
      }>;
      "pagefind-results": PagefindElementProps<{
        instance?: string;
        "show-images"?: string;
        "hide-sub-results"?: string;
        "max-sub-results"?: string;
        "max-results"?: string;
        "link-target"?: string;
      }>;
    }
  }
}

export {};
